{
  "name": "test_worst_opcode.py::test_worst_log_opcodes[fork_Prague-benchmark-gas-value_10M-blockchain_test_from_state_test-fixed_offset_True-non_zero_topic-0_bytes_data-log2]",
  "timestamp_completed": "2025-10-03T03:23:58.183087727Z",
  "metadata": {
    "block_used_gas": 10000000
  },
  "execution": {
    "crashed": {
      "reason": "Failed to execute `docker run`: Command \"docker\" \"run\" \"--rm\" \"--env\" \"RUST_LOG=info\" \"--volume\" \"/tmp/.tmpj9ZUoB:/workspace\" \"ere-cli-risc0:0.0.12-7ef4598\" \"execute\" \"--program-path\" \"/workspace/program\" \"--input-path\" \"/workspace/input\" \"--public-values-path\" \"/workspace/public_values\" \"--report-path\" \"/workspace/report\" failed with status: exit status: 125"
    }
  }
}