{
  "name": "test_worst_memory.py::test_worst_calldatacopy[fork_Prague-benchmark-gas-value_60M-blockchain_test_from_state_test-non_zero_data_False-fixed_src_dst_False-10KiB-transaction]",
  "timestamp_completed": "2025-10-02T06:00:32.837183011Z",
  "metadata": {
    "block_used_gas": 60000000
  },
  "execution": {
    "crashed": {
      "reason": "Failed to execute `docker run`: Command \"docker\" \"run\" \"--rm\" \"--env\" \"RUST_LOG=info\" \"--volume\" \"/tmp/.tmpT4H1Am:/workspace\" \"ere-cli-risc0:0.0.12-7ef4598\" \"execute\" \"--program-path\" \"/workspace/program\" \"--input-path\" \"/workspace/input\" \"--public-values-path\" \"/workspace/public_values\" \"--report-path\" \"/workspace/report\" failed with status: exit status: 125"
    }
  }
}